version: '3'
services:
  web:
    build: ./flask_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
  
  pygame:
    build: ./pygame

  numpy_math:
    build: ./numpy_math
    volumes:
      - ./numpy_math/output:/app/output